name: Trigger Deploy on Release

on:
  release:
    types: [published]

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger geonera-deploy
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: igeoaiti/geonera-deploy
          event-type: deploy-services
